### ISSUE TITLE
Semaphore 2 branch recognition not working

### ISSUE THREAD

**Issue by cyrilkyburz** [percy/percy-js#172]
Default branch recognition isn't working for Semaphore 2. I've noticed the problem when the branch shows  ```unknown-branch```  in our Percy builds.

Semaphore Classic uses the variable  ```BRANCH_NAME``` but Semaphore 2 uses ```SEMAPHORE_GIT_BRANCH ```.

Environment Variables docs for
- [Semaphore Classic](https://semaphoreci.com/docs/available-environment-variables.html)
- [Semaphore 2](https://docs.semaphoreci.com/ci-cd-environment/environment-variables/)

**Comment by Robdel12** [comment]
Hey @cyrilkyburz thanks for the issue! If you wanted to submit a PR to update, that'd be rad. If not, in the meantime, you can set `PERCY_BRANCH` manually to `SEMAPHORE_GIT_BRANCH` in your CI's env settings 😃

**Comment by cyrilkyburz** [comment]
Thank you for your quick response.

It would probably be enough to change [line 258](http://github.com/percy/percy-js/blob/4a7c6b2df91b11fac521cea84e53472df9137abb/src/environment.js#L258) from 

```js
      case 'semaphore':
        result = this._env.BRANCH_NAME;
        break;
```

to

```js
      case 'semaphore':
        result = this._env.BRANCH_NAME || this._env.SEMAPHORE_GIT_BRANCH;
        break;
```

But of course it should be tested on both versions of Semaphore and a test should be written. I can't promise that I will have time for that. In the meantime I "quickfixed" it with setting the env in our CI setup.
