### ISSUE TITLE
Husky optional dependency causes git hooks to be installed in consumer projects

### ISSUE THREAD

**Issue by kpdecker** [percy/percy-js#24]
This is arguably a dev dependency and should be removed from the optional deps.

**Comment by kirkstrobeck** [comment]
https://github.com/percy/percy-js/pull/20

**Comment by timhaines** [comment]
Thanks for the extra context, both in the title of this issue, and the node version comment in #20.  Feeling swayed personally. I'll talk with the team about this today and follow up.

Also: https://twitter.com/seldo/status/906594746411319297

**Comment by timhaines** [comment]
Fixed with #20.

**Comment by timhaines** [comment]
Published in [v2.4.2](https://github.com/percy/percy-js/releases/tag/v2.4.2).

**Comment by kpdecker** [comment]
Appreciate it!
