### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by camacho** [percy/percy-js#32]
We are using Percy on a project, and I am trying to explore using the percy-js module for some more custom functionality for the app. Unfortunately, there doesn't seem to be any documentation, despite the link to the percy.io site :(

Is there any plan to publish documentation for this module? Happy to help in any way I can :)

**Comment by timhaines** [comment]
@camacho Hey Patrick!  This is actually a lower level API client that several of our other packages depend on.  What's your front-end built in?  I'm wondering if one of our other clients would be appropriate, or if there's a good reason for you to use this one..
